# Generated by Django 4.2.4 on 2023-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_images',
            field=models.CharField(default='https://images.search.yahoo.com/images/view;_ylt=AwrOp5mU1fZkMQksnwyJzbkF;_ylu=c2VjA3NyBHNsawNpbWcEb2lkA2U2OGVlMGVlNDYwZGY2YjhjZWY5NmEyOTBjNDg1MTkyBGdwb3MDMwRpdANiaW5n?back=https%3A%2F%2Fimages.search.yahoo.com%2Fsearch%2Fimages%3Fp%3Dplaceholder%2Bfood%2Bimage%26ei%3DUTF-8%26fr2%3Dp%253As%252Cv%253Ai%252Cm%253Asb-top%26tab%3Dorganic%26ri%3D3&w=499&h=374&imgurl=www.treicamile.ro%2Fwp-content%2Fuploads%2F2021%2F11%2Ffood-placeholder.png&rurl=https%3A%2F%2Fwww.treicamile.ro%2Fplatouri%2F&size=13.2KB&p=placeholder+food+image&oid=e68ee0ee460df6b8cef96a290c485192&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&fr=&tt=Platouri+-+Restaurant+%26+Teras%C4%83+-+Trei+Camile&b=0&ni=140&no=3&ts=&tab=organic&sigr=OJN4LVqZlG8m&sigb=brCJd1nv9h55&sigi=xClIDuLTc43.&sigt=GmkxyeZ4JOoG&.crumb=aVLBeAh5ihN&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top', max_length=500),
        ),
    ]
