# Generated by Django 4.2.4 on 2023-09-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_images',
            field=models.CharField(default='https://www.treicamile.ro/wp-content/uploads/2021/11/food-placeholder.png', max_length=500),
        ),
    ]
