# Generated by Django 4.2.4 on 2023-09-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_item_item_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_images',
            new_name='item_image',
        ),
    ]
